;;; geben-helm-projectile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from geben-helm-projectile.el

(autoload 'geben-helm-projectile-open-file "geben-helm-projectile" "\
Find a file in the current project using helm-projectile to open it.

Use a prefix ARG to force a cache refresh.

(fn &optional ARG)" t)
(register-definition-prefixes "geben-helm-projectile" '("geben-helm-projectile-version"))

;;; End of scraped data

(provide 'geben-helm-projectile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geben-helm-projectile-autoloads.el ends here
